name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Copy files to EC2
      - name: Copy files to EC2
        run: |
          scp -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no index.html ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/
