name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        # Create a file for the SSH key and set the right permissions
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > my-aws-key.pem
        chmod 600 my-aws-key.pem

    - name: Copy files to EC2
      run: |
        # Using the private key to copy files over to EC2 instance
        scp -i my-aws-key.pem -o StrictHostKeyChecking=no index.html ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
