name: Deploy HTML Page to AWS EC2

on:
  push:
    branches:
      - main  # Trigger deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      # Step 3: Copy files to EC2
      - name: Copy files to EC2
        run: |
          scp -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no index.html ec2-user@13.212.99.124:/home/ec2-user/

      # Step 4: SSH to EC2 and deploy
      - name: SSH to EC2 and deploy
        run: |
          ssh -i ${{ secrets.AWS_SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no ec2-user@13.212.99.124 << 'EOF'
            sudo mv /home/ec2-user/index.html /usr/share/nginx/html/
            sudo systemctl restart nginx
          EOF
