name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Stage
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (if you are using Node.js)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Run build
      run: |
        npm run build  # Add this if your project has a build step (e.g., React, Next.js, etc.)

  # Test Stage
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js (if you are using Node.js)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test  # Run tests for your application, adjust for your project setup.

  # Deploy Stage
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # This ensures deployment only happens after build and test are successful.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        # Create a file for the SSH key and set the right permissions
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > my-aws-key.pem
        chmod 600 my-aws-key.pem

    - name: Copy files to EC2
      run: |
        # Using the private key to copy files over to EC2 instance
        scp -i my-aws-key.pem -o StrictHostKeyChecking=no index.html ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/
